name: Update Notion Task Labels

on:
  workflow_dispatch:  # Run manually
  schedule:
    - cron: '0 6 * * *'  # Optional: runs daily at 6:00 AM UTC

jobs:
  run-notion-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Notion automation script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node notion-script.js
